name: CI
on: [push,workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: JDK 17 setup
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Clean and Build
        run: ./gradlew clean build --info -x test

      - name: Test
        run: ./gradlew test