name: CI
on: [push,workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      
        
      - name: JDK 17 setup
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Clean and Build
        run: ./gradlew clean build --info -x test
        
      - name: create docker image for application
        run: docker build -t sping-app . 
        
      - name: run docker compose
        run: docker-compose up -d

      - name: stop app container
        run: docker-compose down spring-app
        
      - name: Test
        run: ./gradlew test
        
      - name: Stop containers
        run:  docker-compose down
